/* tslint:disable */
export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  home_works: 'Home Works!',
  aside: {
    administrator: 'Administrator',
    dashboard: 'Dashboard',
    sales: 'Sales',
    gift_card: 'Gift card',
    customer: 'Customer',
    purchases: 'Purchases'
  },
  topbar: {
    back_to_administrator: 'Back to Administrator',
    back_to_item_manager: 'Back to Item Manager',
    back_to_close_till: 'Back to Close Till',
    back_to_banking: 'Back to Banking',
    back_to_items_list: 'Back to Items List',
  },
  buttons: {
    back_to_item_manager: 'Back to Item Manager',
    complete_task: 'Complete Task',
    save_custom_template: 'Save custom template',
    export_template: 'Export for adding bulk items',
    add_new_column: 'Add new column',
    submit: 'Submit',
    complete_end_of_day: 'Complete End Of Day',
    print_z_and_close: 'Print Z and close till',
    enter_cash_amount: 'Enter cash amount',
    enter_float: 'Enter float',
    confirm: 'Confirm',
    cancel: 'Cancel',
    create_new_customer: 'Create new customer',
    complete: 'Complete',
    calculate_amount: 'Calculate Amount',
    no_thanks: 'No, Thanks',
    yes: 'Yes',
    next: 'Next',
    complete_banking: 'Complete Banking',
    yes_please: 'Yes, please',
    no_later: 'No, I\'ll do it later',
    gotcha: 'Gotcha!',
    view_reason: 'View Reason',
    check_gift_card: 'Check Gift Card',
    create_gift_card: 'Create Gift Card',
    log_out: 'Log Out',
    change_user: 'Change User'
  },
  labels: {
    email: 'E-mail',
    customer_name: 'Name',
    phone_number: 'Phone number',
    customer_number: 'Cust num',
    date_of_birth: 'Date of birth',
    country: 'Country',
    city: 'City',
    address: 'Address',
    zipcode: 'Zipcode',
    female: 'Female',
    male: 'Male',
    payment: 'Payment',
    cash: 'Cash',
    gift_card: 'Gift Card',
    credit_card: 'Credit Card',
    eft: 'EFT',
    total: 'Total',
    subtotal: 'Sub-total',
    tax: 'Tax',
    discount: 'Discount',
    qty: 'Qty',
    till_number: 'Till #',
    item_name: 'Item Name',
    unit: 'Unit',
    price: 'Price',
    name: 'Name',
    sku: 'SKU',
    on_hand: 'On Hand',
    enter_manual_amount: 'Enter Manual Amount',
    expected_amount: 'Expected amount',
    actual_amount: 'Actual amount',
    variance_amount: 'Variance amount',
    total_amount: 'Total amount',
    till_machine: 'Till Machine',
    week_no: 'Week No:',
    date: 'Date',
    item: 'Item',
    trans_num: 'Trans. Num.',
    qty_sold: 'Qty Sold',
    tender: 'Tender',
    sales_price: 'Sales Price',
    cost_price: 'Cost Price',
    profit: 'Profit',
    vat: 'Vat',
    total_sale_net_value: 'Total Sale / Net Value',
    refunds: 'Refunds',
    returns: 'Returns',
    voids: 'Voids',
    discounts: 'Discounts',
    promotions: 'Promotions',
    paid_in: 'Paid In',
    paid_out: 'Paid Out',
    mark_up: 'Mark Up',
    mark_down: 'Mark Down',
    open: 'Open',
    closed: 'Closed',
    banking_number: 'Banking Number',
    banked_amount: 'Banked Amount',
    total_variance_amount: 'Total Variance Amount',
    completed_by: 'Completed By',
    includes_float: 'Includes Float',
    total_for_the_day: 'Total for the Day',
    reason_code: 'Reason Code',
    inc_float: '(Inc Float)',
    banking: 'Banking',
    note: 'Note',
    total_sales: 'Total Sales',
    banking_date: 'Banking Date',
    initial_value: 'Initial Value',
    remaining_value: 'Remaining Value',
    expires: 'Expires',
    add_custom_value: 'Add Custom Value',
    barcode: 'Barcode',
    user_information: 'User Information',
    till: 'Till',
    logged_on: 'Logged On',
    sales: 'Sales',
    units: '%0 units',
    from: 'From',
    to: 'To',
    no_results: 'No items found.',
    no_options: 'No results'
  },
  item_manager: {
    header: 'Item Creation - Select an option',
    custom_template_h3: 'Choose a custom template',
    custom_template_p: 'Select this option if you want to choose a template that you already made.',
    recommended_template_h3: 'Choose a recommended template',
    recommended_template_p: 'Select this option to use one of Baikingu\'s recommended templates, it can be modified.',
    import_file_h3: 'Import a file of item data',
    import_file_p: 'If you want to import data from an exported Baikingu template, use this option.',
    custom_template_standard_btn: 'Bulk of standard items',
    custom_template_fashion_btn: 'Fashion items at O\'Lareys',
    recommended_template_standard_btn: 'Standard items',
    recommended_template_fashion_btn: 'Fashion items',
    import_file_btn: 'Choose file'
  },
  item_manager_add: {
    header: 'Item Creation - Create an item',
    library: 'Library'
  },
  product_columns: {
    barcode: 'Barcode',
    sku: 'Sku',
    product_name: 'Product name',
    brand: 'Brand',
    department: 'Department',
    family: 'Family',
    stock_location: 'Stock location',
    style: 'Style',
    color: 'Color',
    size: 'Size',
    season: 'Season',
    cost_price: 'Cost Price',
    selling_price: 'Selling price',
    tax: 'Tax',
    quantity: 'Quantity',
    minimum_quantity: 'Minimum quantity'
  },
  choose_columns: {
    barcode: 'Choose Barcode',
    brand: 'Choose Brand',
    department: 'Choose Department',
    family: 'Choose Family',
    stock_location: 'Choose Stock location',
    style: 'Choose Style',
    color: 'Choose Color',
    size: 'Choose Size',
    season: 'Choose Season',
    cost_price: 'Choose Cost Price',
    selling_price: 'Choose Selling price',
    tax: 'Choose Tax',
    quantity: 'Choose Quantity',
    minimum_quantity: 'Choose Minimum quantity'
  },
  add_column_item: {
    add_new_brand: 'Add new brand',
    add_new_department: 'Add new department',
    add_new_family: 'Add new family',
    add_new_stock_location: 'Add new Stock Location',
    add_new_tax: 'Add new tax',
    add_new: 'Add new'
  },
  errors: {
    field_required: 'This field is required'
  },
  pagination: {
    page: 'PAGE'
  },
  dialog_attribute_value: {
    edit_or_create: 'Edit or create new'
  },
  products_list: {
    items: 'Items',
    item: 'Item',
    search_for_items: 'Search for item'
  },
  item_manager_base: {
    header: 'Item management - select an option',
    view_item: 'View item',
    view_item_p: 'If you wish to check out details on an item, choose this option.',
    view_item_btn: 'View item',
    create_single: 'Create single item',
    create_single_p: 'If you wish to create just one item quickly in Baikingu, use this option.',
    create_new_item: 'Create new item',
    create_bulk: 'Create a new item (bulk)',
    create_bulk_p: 'If you wish to create more than one item, select this option.',
    create_bulk_items: 'Create new items (bulk)'
  },
  login_form: {
    username: 'username',
    password: 'password',
    lost_password: 'Lost password?',
    login: 'log in'
  },
  edit_product: {
    make_default: 'make default image',
    delete_image: 'delete image',
    add_new_image: 'add new image',
    cost_price: 'cost price',
    selling_price: 'selling Price',
    quantity: 'quantity',
    margin: 'margin',
    sku: 'sku',
    tax: 'tax',
    barcode: 'barcode',
    description: 'Item Description',
    edit_mode: 'Enable Edit mode',
    confirm_changes: 'Save changes',
    cancel_changes: 'Cancel',
    current_store: 'Current store',
    view_variances: 'View Variances',
    search: 'Search for item',
    item_overview: 'Item overview',
    availability: 'Availability',
    last_purchase: 'Last Purchase Date',
    next_delivery: 'Next Delivery',
    purchase_order: 'Purchase Order',
    prebooked: 'Pre-Booked Customer Orders',
    prepaid: 'Pre-Paid Customer Orders',
    locations: 'Locations',
    store: 'Store',
    distance: 'Distance',
    inventory: 'Inventory',
    items_number: '%0 Items',
    units: 'Units',
    item_attributes: 'Item Attributes',
    estore: 'E-Store',
    local: 'Local'
  },
  admin_panel: {
    admin_panel: 'Administrator panel',
    paid_in_out: 'Paid In / Paid Out',
    open_cash_drawer: 'Open cash drawer',
    start_day: 'Start of day',
    item_manager: 'Item management',
    cash: 'Cash management',
    end_day: 'End of day',
    settings: 'Settings',
    employee: 'Employment manager',
    reports: 'Reports',
    stock: 'Stock'
  },
  sales: {
    list: 'Sales list',
    item_search: 'Item search',
    search: 'Enter barcode or item no...',
    list_header: {
      item: 'Item',
      value: 'Value'
    },
    subtotal: 'Subtotal',
    proceed: 'Proceed to checkout',
    empty_text: [
      'Let’s give the customer fantastic service! :)',
      'Scan or type the product to begin.',
      'No label or tag? Try “Item Search”.'
    ],
    assign_customer: 'Assign customer',
    refund: 'Refund',
    suspend: 'Suspend sale',
    resume: 'Resume',
    void: 'Void sale',
    product_sales_info: 'Product sales information',
    general_product_info: 'General product information',
    general_information: 'General information',
    item_info: 'Item information',
    identification: 'Identification',
    quantity: 'Quantity',
    qty: 'Qty',
    discount: 'Discount',
    item_total: 'Item Total',
    product_info: 'Product information',
    stock_numbers: 'Stock numbers for item',
    delivery: 'Delivery / Restock',
    item_variances: 'Item variances',
    variance: 'Variance',
    remove_item: 'Remove item',
    set_quantity: 'Set Quantity',
    enter_quantity: 'Enter Quantity...',
    confirm: 'confirm',
    remove_title: 'Removing %0',
    remove_content: 'Are you sure you want to remove this item from basket?',
    void_sale: 'Void sale',
    specify_reason: 'Specify Reason',
    name: 'Name',
    item_price: 'Item price',
    change_price: 'Change price',
    errors: {
      find_product: 'Cannot find product.',
      add_product_to_basket: 'Cannot add product to basket (error occured).',
    }
  },
  receipt_print: {
    type: {
      sale: 'Sale',
      refund: 'Refund'
    },
    inc: 'inc',
    paid_by: 'Paid By',
    sale: {
      item: 'Item',
      qty: 'QTY',
      total: 'Total',
      subtotal: 'Subtotal',
      change_due: 'Change Due',
      saleperson: 'Sale person',
      transaction_number: 'Tran. No.',
      store_at_till: 'Store@TillID',
      date: 'Date'
    },
    refund: 'Refund',
    report: {
      report: 'Report',
      ref_no: 'Ref No.',
      date: 'Date',
      till_id: 'Till ID',
      time: 'Time',
      cost_of_goods: 'Cost of Goods',
      markup: 'Markup (inc VAT)',
      cash: 'Cash',
      gift_card: 'Gift Card',
      card_payments: 'Card payments',
      discounts: 'Discounts',
      voids: 'Voids',
      refunds: 'Refunds',
      opening_cash_amount: 'Opening cash amount',
      closing_cash_amount: 'Closing cash amount',
      customer_count: 'Customer Count',
      customer_receipts: 'Customer Receipts',
      number_of_items: 'No. of items',
      avg_turnover: 'Avg turnover per sale',
      avg_item: 'Avg item per sale',
      cash_drawer_openings: 'Cash drawer openings',
      total_gross: 'Total gross sales',
      total_net: 'Total net sales',
      total_tax: 'Total TAX'
    },
    suspend: {
      header: 'Transaction Suspended',
      saleperson: 'Saleperson',
      transaction_number: 'Trans No.',
      store_at_till: 'Store@TillID',
      date: 'Date'
    },
    start_of_day: {
      header: '*** Start of Day Completed ***',
      saleperson: 'Saleperson',
      transaction_number: 'Trans No.',
      store_at_till: 'Store@TillID',
      date: 'Date',
      from: 'From',
      float: 'Float Amount',
      till: 'Till %0'
    },
    gift_card: {
      header: 'Congratulations on your Gift Card!',
      gift_card_value: 'Gift Card Value',
      valid_until: 'Valid until',
      issued: 'Issued',
      gift_card_no: 'Gift Card Num.'
    }
  },
  customers: {
    assign_customer: 'Assign customer',
    create_customer: 'Create new customer',
    search_customers: 'Search for name, phone etc...',
    phone_error: 'Type a valid international phone number.'
  },
  tills: {
    till_machine: 'Till Machine #',
    till_closing: 'Till Closing',
    till_machine_number_end_of_day: 'Till Machine #%0 - End of Day',
    go_to_next: 'Go to next till',
    till_number: 'Till number',
    till_status: 'Till status'
  },
  end_of_day: {
    header: 'End of Day',
    step1_label: 'Step 1',
    step1_header: 'Print Z Report & Close Till',
    step1_description: 'Push the button to print the z report and automatically close the till',
    step2_label: 'Step 2',
    step2_header: 'Enter Cash Amount',
    step2_description: 'Enter cash amount found in till including gift vouchers',
    step3_label: 'Step 3',
    step3_header: 'Enter Float Amount',
    step3_description: 'Enter the float amount put back into the cash register',
    float_amount: 'Float Amount...',
    enter_float: 'Enter Float',
    day_ended_header: 'Let\'s store that cash',
    day_ended_do_banking: 'Would you like to also do Banking now?',
    already_completed: 'End of Day has already been completed',
  },
  checkout: {
    return_to_item_sale_list: 'Return to item sale list',
    remaining_to_pay: 'Remaining to pay',
    change_due: 'Change due',
    running_total: 'Running total',
    total_to_pay: 'Total to Pay',
    enter_manual_amount: 'Enter manual amount',
    scan_gift_card: 'Scan Gift Card',
    reference_code: 'Reference Code'
  },
  start_of_day: {
    header: 'Start of Day',
    count: 'Count',
    coins: 'Coins',
    notes: 'Notes',
    summary: 'Summary',
    in_the_till: 'in the Till',
    dollar_coins: 'Dollar coins',
    half: 'Half',
    quarter: 'Quarter',
    dime: 'Dime',
    nickel: 'Nickel',
    cents: 'Cents',
    dollar: 'Dollar',
    running_total: 'Running total',
    print_receipt: 'Print Receipt',
    receipt_prompt: 'Do you want to print a start of day receipt?',
    already_completed: 'Start of Day has already been completed',
    counting_error: 'Float does not match end of day closing float, please recount or press confirm to continue and accept variance.',
    do_before_sales: 'Hold your horses! In order to start selling you need to perform "Start of Day". Would you like to do it now?'
  },
  item_search: {
    search_for_item: 'Search for Item',
    cant_find_item: 'Can\'t find item?',
    search_or_scan: 'Search or Scan Item',
    search_result_placeholder: 'You haven’t searched for an item',
    basket_placeholder: 'Your basket is empty',
    items_added: 'Items Added',
    add_items: 'Add Selected Items'
  },
  refunds: {
    header: 'Refund',
    header_receipt: 'Refund - TRN: %0',
    scan_receipt: 'Scan receipt or type transaction number',
    no_receipt: 'No receipt? No Problem!',
    item_name: 'Item Name',
    original_qty: 'Original Qty',
    refund_qty: 'Refund Qty',
    prev_return: 'Prev Return',
    refund_price: 'Refund Price',
    reason_code: 'Reason Code',
    next: 'Next',
    sku: 'SKU',
    complete: 'Complete',
    qty_refunded: 'Qty Refunded',
    reason: 'Reason',
    total_refund_price: 'Total Refund Price',
    location: 'Location',
    date: 'Date',
    total_refund_value: 'Total Refund Value',
    items: '%0 items',
    wrong_length: 'Barcode must be %0 characters long',
    not_found: 'Receipt with given barcode not found.'
  },
  suspend: {
    header: 'Suspend sale',
    content: 'Are you sure you want to suspend the sale?'
  },
  resume: {
    header: 'Resume Sale',
    scan_receipt: 'Scan receipt or type receipt number',
  },
  discount: {
    item_discount: 'Item Discount',
    item_discount_summary: 'Item Discount Summary',
    original_price: 'Original Price',
    discount_price: 'Discount Price',
    savings: 'Savings',
  },
  banking: {
    float_amount_for_till: 'Float Amount for this Till is:',
    banking_statement: 'Banking Statement',
    bank_number: 'Bank number',
    banking_number: 'Banking number',
    banking_amount: 'Banking amount',
    variance_reason: 'Variance reason',
    bank_number_placeholder: 'Add digits here...',
    banking_amount_placeholder: 'Add amount moved to bank...',
    variance_reason_placeholder: 'Type your reason for the variance here...'
  },
  pos_select: {
    header: 'Select the till you are on',
    lets_start: 'Let\'s start selling!',
    till: 'Till #%0'
  },
  adhoc: {
    header: 'Select department',
    item_name: 'Item name',
    item_price: 'Item price',
    item_tax: 'Item tax',
    enter_name: 'Enter name',
    enter_price: 'Enter price'
  },
  reports: {
    item_list_audit: 'Item List for Audit Report',
    audit_summary_header: 'Audit Summary for time period'
  },
  report_banking: {
    search_placeholder: 'Search for Banking Report'
  },
  gift_card: {
    gift_card_sales: 'Gift Card Sales',
    gift_card_sales_description: 'Create a gift card for a customer by either selecting a fixed standard amount or manually typing in the specific amount that the customer wants.',
    gift_card_enquiries: 'Gift Card Enquiries',
    gift_card_enquiry: 'Gift Card Enquiry',
    gift_card_enquiry_description: 'Scan, swipe or key the Gift Card Number or barcode to check the balance.',
    gift_card_information: 'Gift Card Information',
    scan_or_type: 'Scan or type Gift Card number',
    scanning_error: 'Gift Card not recognized, try again.',
    wrong_length: 'Barcode must be %0 characters long.',
    check_gift_card: 'Check Gift Card'
  },
  stock: {
    header: 'Stock',
    supplier: 'Supplier',
    suppliers: 'Suppliers',
    supplier_p: 'Check out your suppliers and make sure you got the best ones',
    management: 'Stock management',
    management_p: 'Managing stock can be daunting, we\'ve made it ease for you to handle.'
  },
  stock_adj: {
    reduced: 'Stock reduced',
    added: 'Stock added',
    moved: 'Stock moved',
    total: 'Total Stock Adjustment',
    stock_adj_no: 'Stock adj. number',
    date_created: 'Date created',
    status: 'Status',
    total_items: 'Total items',
    total_cost: 'Total cost',
    completed_by: 'Completed by',
    search: 'Search for Stock Adj. Number',
    new_adj: 'New stock adj.'
  }
};
